#!/usr/bin/env ruby
# puts the current scrum sprint week number combination

require 'date'

week = Time.now.to_date.cweek
next_week = 0

if week.odd?
  next_week = week + 1
else
  next_week = week
  week = week - 1
end

def format(number)
  sprintf("%02i", number)
end

def release_version
  ENV['NP_RELEASE_VERSION'] || match_version
end

def match_version
  regex = /\Ar\d+\.\d+(\.\d+)?/
  branches = `git branch`.split.select do |branch_name|
    branch_name =~ regex
  end.sort.last.to_s.match(regex)
end

puts "#{release_version}-s#{format(week)}_#{format(next_week)}"
